### ISSUE TITLE
关于博客评论的疑问

### ISSUE THREAD

**Issue by zzugbb** [dongyuanxin/theme-bmw#10]
你好，最近试用了这个博客主题，感觉很棒，但是有个关于评论的问题。

* 别人评论了博主的代码，但是博主好像没有途径可以收到这个信息，除非在评论的页面上看到对应内容。
* 若回复了别人的评论，那么被回复人如何能收到通知，除非在评论的页面上看到对应内容。

就是现在对这个有点疑惑，测试发现没有好的方法，请赐教。

**Comment by zirnc** [comment]
这些属于评论系统的问题，你可以前往评论的项目提出 issue，他们给的解决方案会更加专业。

**Comment by zzugbb** [comment]
好的，谢谢
