### ISSUE TITLE
右侧的目录怎么用？

### ISSUE THREAD

**Issue by jnuse** [dongyuanxin/theme-bmw#14]
如题

**Comment by jnuse** [comment]
懂了，大神无视，hexo新手看这里https://hexo.io/zh-cn/docs/helpers#toc

**Comment by dongyuanxin** [comment]
**抱歉**，过年期间没看代码。
其次，感谢提醒。没发现有这个`API`。主题目前的方法是由jq动态地解析和创建TOC。
