### ISSUE TITLE
如何实现“博客已萌萌哒运行了多久”求明示

### ISSUE THREAD

**Issue by xiahibb** [dongyuanxin/theme-bmw#20]
好喜欢您网站下面的计时器啊
求代码
或者您可以告诉我在那吗？
我也想放一个在我的博客下面。O(∩_∩)O谢谢啦

**Comment by dongyuanxin** [comment]
这个是CSS3实现的动画，代码在这：[https://github.com/dongyuanxin/theme-bmw/blob/aafad68cad/source/scss/animation.scss](https://github.com/dongyuanxin/theme-bmw/blob/aafad68cad/source/scss/animation.scss)
