### ISSUE TITLE
文档格式问题（可忽略）

### ISSUE THREAD

**Issue by zirnc** [dongyuanxin/theme-bmw#3]
就是指[中文文档](https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/)的格式规范不太好，可以用 [lint-md](https://github.com/hustcc/lint-md) 检查错误然后纠正一下，😀

（文档给我们 EasyHexo 的时候我还改了好久才符合[标准](https://github.com/sparanoid/chinese-copywriting-guidelines)）

**Comment by dongyuanxin** [comment]
可参考，但不是核心重点哈~

**Comment by zirnc** [comment]
恩！有空的时候整理下就行了，不是大问题
