### ISSUE TITLE
根目录的yml报错

### ISSUE THREAD

**Issue by AweiLoveAndroid** [dongyuanxin/theme-bmw#4]
具体的如图所示。
![default](https://user-images.githubusercontent.com/27602662/49652740-e24ee280-fa6d-11e8-959a-e5bd18a950d7.png)

**Comment by dongyuanxin** [comment]
这个不是本框架的错误，建议了解一下`yml`配置和`hexo`使用。
`yml`配置的时候，`key`之后的冒号要有空格。

FE：
```yml
url: https://www.awei666.tech # 冒号后面有空格
```

**Comment by zirnc** [comment]
Line 16 那里错了，应该是 `url: 你的链接`

**Comment by dongyuanxin** [comment]
@AweiLoveAndroid 请仔细阅读`yml`配置格式规范和`hexo`文档

> 具体的如图所示。
> ![default](https://user-images.githubusercontent.com/27602662/49652740-e24ee280-fa6d-11e8-959a-e5bd18a950d7.png)
