### ISSUE TITLE
footer页脚时间存在问题

### ISSUE THREAD

**Issue by hhongwen** [dongyuanxin/theme-bmw#5]
时间月份应该是0~11，例如_config.yml的start参数为2018-12-12，则时间显示负30天...
修改footer.ejs第29行为如下内容或者在其它位置修改
`const startTimestamp = new Date(<%- footerStartTime.year %>, <%- footerStartTime.month - 1%>, <%- footerStartTime.day %>).getTime();`

**Comment by dongyuanxin** [comment]
Thanks, and I have fixed it at `version4.0.2`.
Download and use now: https://github.com/dongyuanxin/theme-bmw/releases/tag/v4.0.2

**Comment by dongyuanxin** [comment]
Bug has fixed.
