### ISSUE TITLE
这个主题如何设置置顶

### ISSUE THREAD

**Issue by iathanasy** [dongyuanxin/theme-bmw#9]
我看到博主的文章是可以置顶的，但是文档说明里面没有写该如何置顶。

**Comment by zirnc** [comment]
这种问题在网上很容易搜到，而且是插件问题，不关主题的事。

**Comment by dongyuanxin** [comment]
> 我看到博主的文章是可以置顶的，但是文档说明里面没有写该如何置顶。

@iathanasy 请看 @ChungZH 的解答

**Comment by allegory520** [comment]
博主，你的博客自定义链接type属性页面不能正常访问，麻烦博客费费心，帮忙修复一下
